name: 'Zola Deploy to Pages Up to date'
description: 'Build and deploy a Zola site to GitHub Pages'
author: 'Shaleen Jain'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'zap'  
  color: 'green'
